### ISSUE TITLE
Where is achievements menu?

### ISSUE THREAD

**Issue by ghost** [Barsonvenus/Memories-of-Self-Care-and-Literature#15]
I can't find it anywhere. There's no "interact" menu.

**Comment by Barsonvenus** [comment]
It may require a restart of the game; it doesn't appear right away after the first conversation you have with Monika about achievements. It may also take one or two restarts. Note that the 'interact' menu is a dialogue topic; it's not a unique menu on it's own.

**Comment by ghost** [comment]
I've restarted it several times. It's a dialogue topic? So it would be under "Hey, Monika..."?

**Comment by Barsonvenus** [comment]
That's right.

**Comment by ghost** [comment]
It's not anywhere. Do I have to be at a specific affection?

**Comment by Barsonvenus** [comment]
If you've got the initial 'achievements' conversation where Monika said she'd unlock it, it should be pushed afterwards. 

I took a look and it's not unlike any other dialogue topic in the 'interact' sub-menu, although from what I understand you haven't unlocked any other topic under the interact sub-menu, so it's hard to say what could be happening here. How MAS pushes topics can be a bit weird, in my experience. 

I've gotten into the habit of providing workarounds to force the topic appearing as long as you re-run the topic. I'll do the same here, so I might need to make a updated file for you in the meantime.

**Comment by Barsonvenus** [comment]
Here's a updated file to unzip; delete the SCLachievements.rpy file and replace it with this one and rerun the 'Achievements' topic. Let me know if you encounter any other issues:

[SCLachievements.zip](https://github.com/Barsonvenus/Memories-of-Self-Care-and-Literature/files/12667523/SCLachievements.zip)

**Comment by ghost** [comment]
Thank you so much! I'll let you know if it works.

**Comment by ghost** [comment]
...nope. I've looked multiple times, and readded it. I still can't figure it out.

**Comment by Barsonvenus** [comment]
Even after actually having the achievement menu be actively pushed through re-running the achievements topic? 

edit: okay, I think I've figured out an error on my end; try searching for the topic under 'repeat conversation' or searching for the topic manually in MAS's topic search bar. The quickest way to do so is just search for 'achievement.'

I'm not entirely sure what could the issue could be. the topic appearing under 'repeat conversation' appears to actually be a bug as part of the backdoor! it appears other users are managing to unlock the achievements menu, so in this specific case I might need to just provide another updated file for you specifically. definitely going to keep an eye on this as MAS's topic unlocking system has always been iffy and I definitely want to make sure it works properly.

**Comment by ghost** [comment]
Mm, still not working. I'm sorry about this whole thing! I know a little Ren'Py, so it should be easy enough to fix it myself by making it constantly unlocked.

**Comment by ghost** [comment]
It's finally fixed! Your code worked perfectly, I just had difficulty implementing it. Thank you so much!

**Comment by Barsonvenus** [comment]
Hey, no need to apologize for sending out bug reports. I'm not a coder so bug reports are appreciated so I can provide a seamless experience for everybody. Thanks for working with me on this bug report as well.

I'm a little curious because I'm not entirely sure what I could have fixed, hahaha. Is the 'Check Achievements' dialogue option available in the regular 'Hey, Monika...' menu, or is it in the 'Repeat Conversation?' menu?

**Comment by ghost** [comment]
I wasn't ever able to find it, but using your new code I can ask Monika to repeat it and she'll just open it up for me. So I guess it wasn't completely solved, ahaha. But enough that I could get to the menu.

**Comment by Barsonvenus** [comment]
I do feel like that might be too inconvenient for you; I can provide one more file with the code updated so that the Achievement Menu is just unlocked from the very start, no need to run the 'Achievement' topic. 

If that doesn't work, then at this point I wouldn't know what else to do, unfortunately. At the very least, I'll make the backdoor function easier to use for the full release at least so you don't have to hear Monika give the entire speech every time you need to use the achievement menu..

I'll be closing the ticket as the issue appears unique att, but you should be able to leave any last comments if needed. Thanks again for reaching out and for supporting the submod!

[SCLachievements.zip](https://github.com/Barsonvenus/Memories-of-Self-Care-and-Literature/files/12681155/SCLachievements.zip)
