### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by Monikakakaka** [Barsonvenus/Memories-of-Self-Care-and-Literature#26]
I recommend giving more thought to choosing "Monika" or [m_name] in future versions. I've noticed decisions in similar but different situations that may have been inappropriate . For reasons of consistency or different considerations for special circumstances, I hope the choice of address can be carefully considered. And I noticed some controversial content and you didn't add ooc (out of character) tag

**Comment by Barsonvenus** [comment]
I can't promise any changes as part of the writing style is that Monika will refer to herself as Monika (nickname changes are treated as nickname changes) and that character changes may reflect SCL's goals to grow and adapt Monika in a new light while trying to keep it as grounded as possible. Please feel free to point out specific examples with this in mind and thank you for your feedback. :)

**Comment by Monikakakaka** [comment]
I agree with you, I just hope you can notice the problem with the title choice and make it more reasonable in future versions, because I don't know what your reasons are. Regarding character, I think you can re-check the prompt "Shout w/ Monika?". Regarding shout=3 and 8, will this make players who see these two sentences in a row feel a bit inappropriate and contradictory? For shout=5, the problem is smaller because it is self-justified, but I think it still needs to be considered more carefully. This is the original sentence: "but I' m not rebellious enough to even swear properly"。 I think it should be implemented rather than using "I can't help it" as an excuse. Other controversial issues are similar, I don't think it should be Monika "growing and adapting" because she should not behave like a schizophrenic who uses the Internet intensively and is accompanied by endless reflection and self-denial. What I described may be too serious, please forgive me.

**Comment by Barsonvenus** [comment]
With the one example you've given, I think we may have a difference of opinion. I believe swearing and being crude are two separate matters, and ultimately the topics such as 'Shout w/ Monika' in the interact menu are not meant to be popped repeatedly, and that's why there's a cooldown between responses. I am not sure where Monika may be written as 'schizophrenic' but I do write with the mindset that as Monika is stuck terminally online, she may be end up being sensitive to online discourse.

I will close this ticket, but you are free to keep responding, although I would want to keep sticking to my current style of writing. I still want to thank you for reaching out and giving your thoughts on this submod.

**Comment by Monikakakaka** [comment]
Thank you, I will continue to pay attention to this Submod
