### ISSUE TITLE
Can conversation topics be made bookmarkable/derandomable?

### ISSUE THREAD

**Issue by DaleRuneMTS** [Barsonvenus/Memories-of-Self-Care-and-Literature#6]
It's not a huge deal if you don't know how right now, but would it be possible in a future patch for you to make the conversation topics able to be bookmarked and derandomed? I'm on Repeat Conversations, Monika's leg won't stop cramping, and I'd like to be able to derandom that topic so she no longer has to proverbially put up with it.

**Comment by Barsonvenus** [comment]
Yeah, it appears that a majority if not all topics in this submod are iffy with bookmarks/derandomization, and I've never really figured out why. I might be overlooking something simple so I'll definitely take a look into that for the future as it is a bit of a low-priority issue for me depending if it's a easy fix.

Right now, curating current topics to include being de-randomed by default should be far easier because there's already some topics that do that. I would agree that the cramping topic is one worth de-randomizing and I'll push that for next release.

Or maybe I'll amend it so repeated viewings have different dialogue. I've been tinkering with that too.

**Comment by Barsonvenus** [comment]
After looking into it a bit more, MAS allows only certain topic prefixes to be bookmarked; since SCL uses it's own prefixes (which is ultimately the right practice if I understand right) I have to manually add bookmarks and de-randoming options to pretty much all my topics unless I figure out how MAS allows prefixes, which appears to be trickier.

Otherwise, from here on out I'll start liberally adding these bookmarks/de-randomizing options to appropriate topics (repeatable topics will be bookmarkable, sensitive topics with impact when viewed once available for re-randomization, etc)

**Comment by DaleRuneMTS** [comment]
For what it's worth, here's the workaround I've been taught in the past; maybe it will work for you too, but I know Python can be fickle sometimes, so this is tentative.

`init 5 python in mas_bookmarks_derand:
    # Ensure things get bookmarked and derandomed as usual.
    label_prefix_map["***_"] = label_prefix_map["monika_"]`
With *** substituted by SCL or whatever prefix you use, perhaps?

**Comment by Barsonvenus** [comment]
You've provided a elegant solution right there! That should work and I can add that for next release. Much appreciated!

That said, this is still a good reminder to add 'derandom' tags to the end of certain topics, so I'll also pay attention to that. As mentioned, I do feel like certain topics absolutely count.
