### ISSUE TITLE
Typos and confusing word choice.

### ISSUE THREAD

**Issue by SirStylus** [Barsonvenus/Memories-of-Self-Care-and-Literature#9]
Hey there! I just started playing this submod and I'm intrigued! So far I haven't seen many instances of out-of-character writing or typos. That said nobody's perfect. I wanted to help the mod author out by documenting the errors I noticed as well as proposing fixes.

This will contain spoilers for the mod contents, only proceed if you do not care about spoilers or if you wrote the mod.

I lost the history so I don't have the dialogue attached and it may have been relevant at the moment, but early in the mod, Monika refers to herself as "Monika" rather than fetching the nickname. In context, it could have been that Monika was referring to "After all I'm still 'A' Monika" as in she still has her old history even if she has a new life and identity. If so there is no error to report. I want to point it out just in case, however, so the author knows about fetching the nickname.

In the dialogue tree that begins: "'Secrets, silent, stony sit in the dark palaces of both our hearts:" the line "Part of how I want our relationship to be as smooth as silk is that I want to be someone you can absolutely trust." seems a little ineloquent. Perhaps launching directly into the line with "I want our relationship to be as smooth as silk and yet... I feel we can only reach that point if show you I can be someone you can trust absolutely." I might also suggest dropping the simile and instead choosing a stronger synonym for smooth that could be better applied. Perhaps "I want our relationship to be effortless and yet..." This is a petty suggestion, I just think this line could be written stronger.

In the same dialogue tree as before: "And right now? I haven't even articulated most of my questions about this game, yet alone tried to find answers." There are two ways I could interpret this. Either "yet" was a typo for "let" as in "let alone" or the typo was forgetting the "I" after "yet" so it would read "about this game, yet I alone tried to find answers." Between the two the former makes the most logical sense since Monika hasn't been trying to find answers alone. I'd recommend the line be changed to "And right now? I haven't even articulated most of my questions about this game, let alone tried to find answers." but the line "And right now? I haven't even articulated most of my questions about this game, yet I alone tried to find answers." would also grammatically fit, even if it doesn't account for the fact that other forces are also trying to uncover secrets about DDLC.

There are a number of situations where the author wanted to use an ellipsis (...) but instead simply used two periods (..). As far as I know, two-dot ellipsis are only informally recognized, but even if this weren't the case there are other cases in which the correct three-dot ellipsis is used. I recommend making this consistent across all instances of ellipsis.

A similar rule that I actually didn't know before JUST NOW is regarding the use of dashes/hyphens (-). It turns out there are two kinds; Em dashes and En dashes. Em is for connecting separate thoughts in a similar way to a comma or using parentheses. En is for connecting words. They also are different lengths, Em (—) being longer than En (–) and both being longer than a normal dash (-) (—,–,-). I bring this up because something looked off about the usage of the em dashes being used, so I looked up their usage. In addition to picking the correct length of dash for the use case, formal usage varies but em dashes should typically be used either with no spaces on either side of the dash or with spaces on both sides of the dash. There are a number of instances where em dashes are used in the dialogue where there is no space before the dash and a single space after the dash. No space on either side is the more "proper" way of doing it—MLA and such—while a space before and after the em dash is what newspapers and magazines will typically prefer for clarity and visual appeal — I also prefer it myself for the same reason.

An example of this is with the conversation line: 
"A popular example- perhaps the most common one by western standards? - is the background of the TV show, 'Star Trek;' a franchise about a starfaring ship and its crew." 

It should be changed to either: 
"A popular example—perhaps the most common one by Western standards—is the background of the TV show, 'Star Trek;' a franchise about a starfaring ship and its crew." 

OR: 
"A popular example — perhaps the most common one by Western standards — is the background of the TV show, 'Star Trek;' a franchise about a starfaring ship and its crew."

(As an unrelated change, I believe in that case "Western" is meant to be capitalized, not sure if that's correct.) 

In the dialogue tree about Karma there is a line that reads: "Religion's more confusing aspects could be hand-waved away if it you think about the system being influenced by one, mysterious being." The "it" should be deleted.

In the same tree: "And as cause and effect can be circular, so does your life;" I believe "does" should be replaced with "can". "As [noun 1] can happen, so can [noun 2]" fits better than "As [blank] can happen, so does [blank]" because the sentence is trying to apply the same verb (can) to both nouns instead of separate verbs (can and does) which have different use cases. I suggest changing the line to "And as cause and effect can be circular, so can your life;"

I would honestly recommend a rewrite of the entire karma dialogue tree. There are other small minor issues in this topic that I don't understand the grammatical rules at play well enough to comment on. I don't think the topic is a bad, just that it can be improved. I know that a lot of this mod is about introspection and personal growth, which are conceptually the reasons why I like the idea of Monika After Story to begin with, but this topic felt both grammatically weird to parse and somewhat meandering when it did make sense. I think for it to meander a little bit makes sense, personal development isn't linear after all. It just seems excessive to the point where I didn't fully grasp the point of the topic.

In the topic about hobbies and how much Monika knows: "What I'm in your world, and say I get into a genuine, heated argument with someone?" I believe it should be "What [if] I'm in your world, and say I get into a genuine, heated argument with someone?" I also think it's just a little wordy and could be changed to "What if I get into a genuine, heated argument with someone after crossing over?"

Just to be clear I'm not trying to come off as a nagging pendant. I see potential in this mod and want to help make it shine by helping out with my proofreading. I hope the author knows I appreciate their work and hope they appreciate my input! I'll add more to this as I encounter it.

**Comment by Barsonvenus** [comment]
Hi!

So I appreciate the feedback; it's fascinating to get feedback more akin to proofreading moreso than a bug report which is what I normally expect.

This submod is mostly a way for me to continuously work my writing muscle but I am a hobby writer and I can fully admit my prose is deserving of a lot of improvement. Monika herself would probably be aghast at the idea of proofreading my work, so again I do want to say this sort of feedback is well appreciated.

I'm just gonna tackle your points loosely and out of order as I go through your post.

- This submod purposely interchangeably uses 'Monika' and her nickname. A new topic will probably be introduced to explain this as thought has been put into this relating to Monika's character.

-  Wow, I am rightfully called out for ellipses and I never thought I'd have to explain myself. You are 100% correct in that I should be using three-dot ellipsis and not two-dot ellipses. I will probably make another topic about this because some of it is that there is a general idea that there is an irregular cadence to Monika's speech: specifically, how her moments of silence or hesitance are interpreted through the game. I suppose as of typing this it wouldn't be a concept grasped through its usage alone, hahaha. I'll give the overall concept some further thought.

- I'm going to completely own up to just playing it fast and loose with dashes and hyphens, and considering my liberal semicolon usage which feels like a similarly cowboy concept for writing I will accept needing to actually use dashes and hyphens properly in stride.

- For the typos, awkward structuring, and rewrites: objectively speaking the typos are obvious mistakes, so that's that. For the proposed rewrites, I get where you're coming from (especially regarding the 'Karma' topic; I personally am very fond of the subject matter as a topic, but I would agree it is actually clunky in execution.) Your suggestion regarding the 'Secrets' topic is one I also understand and does touch on thoughts I've had regarding writing Monika's character, although I admit I'm not particularly keen on rewriting it.

Right now the focus for the output of this mod is mostly on just getting content out so I can never give a timeline for tackling these aside from obvious typos but if you are comfortable and if I may make a suggestion, you are free to individually submit individual bug reports for any proofreading as I understand that's how MAS and other related DDLC mods effectively catalogue and handle these issues. It might be less unwieldy than submitting one big bug report as well.

Another suggestion is that you are free to tackle these of your own initiative and submit pushes as I am more than happy to merge fixes and credit any work. If that is indeed how Github works because I'm just a hobby writer, not a coder.

Thanks for the support and taking the time to submit your concerns.

**Comment by SirStylus** [comment]
Hi there again!

I just finished reading your response. I'm also gonna respond a little out of order. 

I have been a little curious about how pushing suggested fixes on GitHub works. I knew it was something possible, but I've not really had a reason to sit down and learn as of yet.

I realize the wall of text I smacked down probably looked a bit daunting in hindsight. When I first posted it was only one error and one suggestion and I just left my game running and whenever I'd encounter more dialogue I wanted to help with I updated this post. I was a little worried about cluttering the page if I submitted each entry separately. I haven't used git a whole lot or had a lot of community interaction, so sorry if I inadvertently did something weird. That all being said: if I know you have a preference in how these kinds of fixes are submitted I would be happy to switch to whatever helps most!

Also I hope the fact that I had multiple suggestions doesn't dissuade you from continuing to create. I really have liked the work so far, genuinely. I've used some other submods where I felt the author didn't even try to match the writing style or personality and rather than go to their GitHubs to report fixes I just uninstalled their content. I feel like this one feels too special to just uninstall. I hope you keep up the good work!

I'm gonna try to learn how to do that code push thing if I continue to make suggestions. Some time after I posted my suggestions I got some really bad news and it's made me not really want to play so I don't know when that'll be. Thanks for your work, I hope you're having a better day than I am.

**Comment by SirStylus** [comment]
I'm sorry, I accidentally pressed the "close" button when submitting that.

**Comment by Barsonvenus** [comment]
Don't worry about feeling weird, I'm not a coder and this is a GitHub repository for a mod of a mod of a niche horror game so no need for formality. And rest assured, this is a passion writing project so I'll write as long as I have something to write and I appreciate the straightforward feedback.

With the particular points you've raised addressed, I'm going to close this ticket. With what you've said about your troubles, I hope everything works out for you.
